services:
  - type: web
    name: trading-app-backend
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: trading-app
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: FLYWAY_ENABLED
        value: true
      - key: JWT_ACCESS_TOKEN_TTL_MINUTES
        value: 15
      - key: JWT_REFRESH_TOKEN_TTL_DAYS
        value: 30
